import {test,expect} from '@playwright/test';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
import {unzipSync,strFromU8} from 'fflate';
async function project(page:any,name:string){
  await page.goto('app');await page.getByRole('button',{name:'New workspace',exact:true}).click();await page.getByLabel('Workspace name').fill(name);await page.getByRole('button',{name:'Create workspace',exact:true}).click();await page.getByRole('button',{name:'Create a project',exact:true}).click();await page.getByRole('textbox',{name:'Project name',exact:true}).fill(name);await page.getByRole('button',{name:'Create project',exact:true}).click();await page.getByRole('button',{name:'Shared forms',exact:true}).click();
}
test('native form editor preserves invalid/interrupted drafts and exports the declarative edit standalone',async({page})=>{
  await project(page,'Shared identity form');
  await expect(page.getByRole('link',{name:'Skip to editor',exact:true})).toBeVisible();await page.getByRole('link',{name:'Skip to editor',exact:true}).click();await expect(page.locator('#project-editor')).toBeFocused();
  await page.route('**/api/form-preview**',async route=>{await new Promise(r=>setTimeout(r,800));await route.continue();});
  await page.getByLabel('Shared form recipe',{exact:true}).selectOption('yrpid-v2');
  await expect(page.getByRole('status').filter({hasText:'Generating the shared form'})).toBeVisible();await page.screenshot({path:test.info().outputPath('shared-form-loading.png')});
  const preview=page.frameLocator('iframe[title="Generated shared form"]');await expect(preview.locator('h1')).toHaveText('Welcome in.');await page.unroute('**/api/form-preview**');
  await page.getByLabel('Generated heading',{exact:true}).fill('A generated identity page');await page.getByLabel('Email field label',{exact:true}).fill('Approved account email');await expect(preview.locator('h1')).toHaveText('A generated identity page');await expect(preview.locator('label[for="email"]')).toHaveText('Approved account email');
  await page.getByLabel('Generated heading',{exact:true}).fill('');await expect(page.getByRole('alert').filter({hasText:'Draft retained'})).toBeVisible();await expect(preview.locator('h1')).toHaveText('A generated identity page');await page.screenshot({path:test.info().outputPath('shared-form-invalid-draft.png')});
  await page.getByText('Advanced shared-form blueprint',{exact:true}).click();await page.getByRole('textbox',{name:'Shared-form blueprint JSON',exact:true}).fill('{invalid raw draft');await page.getByRole('button',{name:'Apply form draft',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'Working content was preserved'})).toBeVisible();await page.screenshot({path:test.info().outputPath('shared-form-source-error.png')});
  await page.reload();await page.getByRole('button',{name:'Shared forms',exact:true}).click();await page.getByText('Advanced shared-form blueprint',{exact:true}).click();await expect(page.getByRole('textbox',{name:'Shared-form blueprint JSON',exact:true})).toHaveValue('{invalid raw draft');await expect(preview.locator('h1')).toHaveText('A generated identity page');
  await page.getByLabel('Generated heading',{exact:true}).fill('Recovered generated heading');await page.getByRole('button',{name:'Save changes',exact:true}).click();await expect(page.getByText(/Saved · Revision 2/)).toBeVisible();await expect(preview.locator('h1')).toHaveText('Recovered generated heading');
  await page.getByLabel('Generated heading',{exact:true}).fill('Discard me');if(await page.locator('.project-actions summary').isVisible())await page.locator('.project-actions summary').click();await page.getByRole('button',{name:'Discard local draft',exact:true}).click();await expect(page.getByLabel('Generated heading',{exact:true})).toHaveValue('Recovered generated heading');
  await page.getByRole('button',{name:'Export',exact:true}).click();const event=page.waitForEvent('download');await page.getByRole('button',{name:'Generated shared form · ZIP',exact:true}).click();const download=await event;const files=unzipSync(await readFile((await download.path())!));expect(strFromU8(files['index.html'])).toContain('Recovered generated heading');expect(strFromU8(files['index.html'])).toContain('Approved account email');expect(strFromU8(files['fixture.js'])).not.toContain('fetch(');
  const dir=test.info().outputPath('standalone-form');for(const[name,bytes]of Object.entries(files)){expect(name.startsWith('/')||name.split('/').includes('..')).toBe(false);const file=join(dir,name);await mkdir(join(file,'..'),{recursive:true});await writeFile(file,bytes);}
  await page.goto(pathToFileURL(join(dir,'index.html')).href);await expect(page.locator('h1')).toHaveText('Recovered generated heading');await page.locator('#email').fill('fixture@invalid.test');await page.locator('#send-link').click();await expect(page.locator('#status')).toContainText('No authentication or transaction');await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:test.info().outputPath('standalone-generated.png'),fullPage:true});
});
test('Go variants render native configuration/card and interrupted previews cannot replace the latest screen',async({page})=>{
  await project(page,'Shared link builder');const choice=page.getByLabel('Shared form recipe',{exact:true});const preview=page.frameLocator('iframe[title="Generated shared form"]');
  await choice.selectOption('go-upstream');await expect(preview.locator('#wrap')).toBeVisible();await expect(preview.locator('.android-card')).toHaveCount(0);await page.getByLabel('URL field label',{exact:true}).fill('Destination URL');await expect(preview.locator('label[for="url"]')).toHaveText('Destination URL');
  await choice.selectOption('yrpid-v2');await choice.selectOption('go-upstream');await choice.selectOption('go-live');await expect(preview.locator('#wrap')).toBeVisible();await expect(preview.locator('.android-card')).toHaveCount(0);
  await preview.locator('.share-options summary').focus();await page.keyboard.press('Enter');await expect(preview.locator('.share-options')).toHaveAttribute('open','');await page.keyboard.press('Tab');await expect(preview.locator('#preview-language')).toBeFocused();await preview.locator('#url').fill('not a URL');await preview.locator('#wrap button').click();await expect(preview.locator('#url')).toBeFocused();
  await page.route('**/api/form-preview**',route=>route.fulfill({status:503,contentType:'application/json',body:'{"error":"Synthetic generation interruption"}'}));await page.getByLabel('Generated heading',{exact:true}).fill('Interrupted generation');await expect(page.getByRole('alert').filter({hasText:'Synthetic generation interruption'})).toBeVisible();await expect(preview.locator('h1')).toHaveText('Create a short link');await page.screenshot({path:test.info().outputPath('shared-form-interrupted-generation.png')});await page.unroute('**/api/form-preview**');await page.getByLabel('Generated heading',{exact:true}).fill('Recovered link builder');await expect(preview.locator('h1')).toHaveText('Recovered link builder');
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:test.info().outputPath('shared-form-editor.png'),fullPage:true});
});
